"""Gate proposal prompt, deduplication, and Phase B gate-pair formatter.

The prompt asks for architectural improvement inside the runtime contract,
without prescribing a network. Like the CV pipeline, it conditions proposals
on a reference artefact and measured feedback when available.
"""

from __future__ import annotations

import re
from contextlib import contextmanager

from .gate_store import structural_hash

GATE_SYSTEM_PROMPT = (
    "You are an expert PyTorch neural network architect designing trainable MoE router gates. "
    "Invent expressive, nonlinear router networks using PyTorch's rich building blocks. "
    "The supplied interface constrains compatibility, not your architectural creativity."
)

# Baseline reference for the first round (heritage: the removed
# Gate_gen_with_gate.json experiment config).
BASELINE_GATE_CODE = (
    "import torch\n"
    "import torch.nn as nn\n\n"
    "class LLMGeneratedGate(nn.Module):\n"
    "    def __init__(self, model_dim: int, num_experts: int):\n"
    "        super().__init__()\n"
    "        self.base = nn.Linear(model_dim, num_experts, bias=False)\n\n"
    "    def forward(self, x: torch.Tensor) -> torch.Tensor:\n"
    "        return self.base(x)\n"
)


def gate_proposal_prompt(shapes, *, reference_source: str = "", feedback: str = "") -> str:
    """Single-reference gate proposal prompt.

    ``reference_source`` and ``feedback`` are optional so round 0 can bootstrap
    from the baseline contract alone.
    """
    reference_block = ""
    if reference_source.strip():
        reference_block = (
            "The current best MoE router gate is:\n"
            f"<gate>\n{reference_source.strip()}\n</gate>\n"
        )
    feedback_block = (
        "Measured results of earlier gate candidates in this run:\n"
        f"{feedback.strip()}\n" if feedback.strip() else ""
    )
    return f"""Generate an improved PyTorch neural network for the router gate of an MoE language model, aiming to improve the image-classification networks generated by that model.

Use the reference gate and measured results below, when available, to improve the network design and address unsuccessful patterns. Develop your own architecture rather than copying the reference.

Design goal:
Invent an expressive, nonlinear network that learns input-dependent routing beyond a single linear projection. Explore PyTorch's compatible layers, trainable operations, and their composition to create a coherent design; choose the internal structure yourself. A plain linear gate, a renamed copy, or extra layers that never influence the output do not meet this design goal. Added computation should provide learnable representational capacity, not complexity for its own sake.
The required self.base is the native-weight interface, not the complete architecture. Matching self.base(x) is an initialization condition only: your network must start with that behavior and be able to learn a richer nonlinear mapping during training. Satisfy both requirements rather than dropping the creative architecture to satisfy initialization. When correcting an implementation error, repair it without reducing the design to the plain linear baseline.

Gate contract:
- Define class LLMGeneratedGate(nn.Module) with __init__(self, model_dim: int, num_experts: int).
- forward(self, x) maps (..., model_dim) to a single tensor of finite raw logits (..., num_experts), processing each token independently and preserving leading dimensions.
- Expose self.base = nn.Linear(model_dim, num_experts, bias=False). The host copies native router weights into it; at initialization the network must reproduce self.base(x) exactly while allowing the added parameters to learn.
- Softmax, top-k, auxiliary loss, and expert dispatch are handled by the host.
- Use only torch imports. Register parameters and layers in __init__; respect the module device and dtype. Forward must be deterministic, without dropout, batch normalization, or random sampling.
- Derive dimensions from model_dim and num_experts. Router shapes: {shapes!r}.

{reference_block}{feedback_block}
Return only the complete Python module between <gate> and </gate>."""


@contextmanager
def gate_prompt_scope(chat_bot):
    """Isolate the gate proposal from any CV system prompt on the chatbot."""
    previous = getattr(chat_bot, "system_prompt", None)
    chat_bot.system_prompt = GATE_SYSTEM_PROMPT
    try:
        yield
    finally:
        chat_bot.system_prompt = previous


_TOKEN_RE = re.compile(r"[A-Za-z_]\w*|[^\s]")
_SHINGLE_N = 7


def code_minhash(code: str, num_perm: int = 128):
    """MinHash over token shingles, used as a near-duplicate *warning* only."""
    try:
        from datasketch import MinHash
    except ImportError:
        return None
    tokens = _TOKEN_RE.findall(code)
    shingle = MinHash(num_perm=num_perm)
    for index in range(max(1, len(tokens) - _SHINGLE_N + 1)):
        shingle.update(" ".join(tokens[index:index + _SHINGLE_N]).encode("utf-8"))
    return shingle


def near_duplicate_similarity(source: str, references: list[str]) -> float | None:
    """Highest MinHash Jaccard against prior gate sources, or None if unavailable.

    Gate code is highly templated, so this is advisory.  Exact duplicates are
    caught by :func:`is_duplicate_gate` using the AST hash.
    """
    candidate = code_minhash(source)
    if candidate is None:
        return None
    best = 0.0
    for reference in references:
        other = code_minhash(reference)
        if other is not None:
            best = max(best, candidate.jaccard(other))
    return round(best, 4)


def is_duplicate_gate(source: str, seen_hashes: set[str]) -> bool:
    """True when the gate's structure is byte-equivalent after normalisation."""
    try:
        return structural_hash(source) in seen_hashes
    except SyntaxError:
        return False


def gate_sft_examples(pairs: list[dict], shapes) -> list[dict]:
    """Phase B supervision: requirements -> higher-scoring gate source.

    Quality selects the target; it is deliberately not shown as an input, so the
    model learns the architecture rather than the score.
    """
    prompt = gate_proposal_prompt(shapes)
    examples = []
    for pair in pairs:
        examples.append({
            "pair_id": pair["pair_id"],
            "messages": [
                {"role": "system", "content": GATE_SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
                {
                    "role": "assistant",
                    "content": "<gate>\n" + pair["higher_source"].strip() + "\n</gate>",
                },
            ],
        })
    return examples
